using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;
using System.Text.RegularExpressions;
using RCLargeLanguageModels.Parsing.ParserRules;

namespace RCLargeLanguageModels.Parsing
{
	/// <summary>
	/// Represents a parsed rule in the AST (Abstract Syntax Tree) generated by parsing a language grammar.
	/// </summary>
	public struct ParsedRule
	{
		/// <summary>
		/// Gets the value of the rule if it was successful.
		/// </summary>
		public readonly bool success;

		/// <summary>
		/// The ID of the rule that was parsed.
		/// </summary>
		public int ruleId;

		/// <summary>
		/// The starting index of the rule in the input text.
		/// </summary>
		public int startIndex;

		/// <summary>
		/// The length of the rule in the input text.
		/// </summary>
		public int length;

		/// <summary>
		/// Gets the value indicating whether this rule represents a token.
		/// </summary>
		public bool isToken;

		/// <summary>
		/// The single token associated with this rule. <see cref="ParsedToken.Fail"/> by default.
		/// </summary>
		public ParsedToken token;

		/// <summary>
		/// Gets the occurency index of this rule within its parent rule. -1 by default.
		/// </summary>
		public int occurency;

		/// <summary>
		/// Gets the children rules of this rule. Valid for parallel and sequence rules.
		/// </summary>
		public List<ParsedRule>? rules;

		/// <summary>
		/// Gets the intermediate value associated with this rule.
		/// </summary>
		/// <remarks>
		/// For <see cref="ChoiceParserRule"/> it will be the selected inner value. <br/>
		/// For <see cref="OptionalParserRule"/> it will be the inner value if present, otherwise null. <br/>
		/// For <see cref="TokenParserRule"/> it will be the inner intermediate value of the token result.
		/// <para/>
		/// For other implementations see remarks for specific implementations. But oftenly it will be <see langword="null"/>.
		/// </remarks>
		public object? intermediateValue;

		/// <summary>
		/// Initializes a new instance of the <see cref="ParsedRule"/> struct.
		/// </summary>
		/// <param name="ruleId">The ID of the rule that was parsed.</param>
		/// <param name="startIndex">The starting index of the rule in the input text.</param>
		/// <param name="length">The length of the rule in the input text.</param>
		/// <param name="token">The single token associated with this rule.</param>
		/// <param name="intermediateValue">The intermediate value associated with this rule.</param>
		public ParsedRule(int ruleId, int startIndex, int length, ParsedToken token,
			object? intermediateValue = null)
		{
			this.success = true;
			this.ruleId = ruleId;
			this.startIndex = startIndex;
			this.length = length;
			this.isToken = true;
			this.token = token;
			this.occurency = -1;
			this.rules = null;
			this.intermediateValue = intermediateValue;
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="ParsedRule"/> struct.
		/// </summary>
		/// <param name="ruleId">The ID of the rule that was parsed.</param>
		/// <param name="startIndex">The starting index of the rule in the input text.</param>
		/// <param name="length">The length of the rule in the input text.</param>
		/// <param name="rules">The children rules of this rule.</param>
		/// <param name="intermediateValue">The intermediate value associated with this rule.</param>
		public ParsedRule(int ruleId, int startIndex, int length, List<ParsedRule> rules,
			object? intermediateValue = null)
		{
			this.success = true;
			this.ruleId = ruleId;
			this.startIndex = startIndex;
			this.length = length;
			this.isToken = false;
			this.token = ParsedToken.Fail;
			this.occurency = -1;
			this.rules = rules;
			this.intermediateValue = intermediateValue;
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="ParsedRule"/> struct.
		/// </summary>
		/// <param name="success">The value of the rule if it was successful.</param>
		/// <param name="ruleId">The ID of the rule that was parsed.</param>
		/// <param name="startIndex">The starting index of the rule in the input text.</param>
		/// <param name="length">The length of the rule in the input text.</param>
		/// <param name="isToken">The value indicating whether this rule represents a token.</param>
		/// <param name="token">The single token associated with this rule.</param>
		/// <param name="occurency">The occurency index of this rule within its parent rule.</param>
		/// <param name="rules">The children rules of this rule.</param>
		/// <param name="intermediateValue">The intermediate value associated with this rule.</param>
		private ParsedRule(bool success, int ruleId, int startIndex, int length,
			bool isToken, ParsedToken token, int occurency, List<ParsedRule> rules,
			object? intermediateValue = null)
		{
			this.success = success;
			this.ruleId = ruleId;
			this.startIndex = startIndex;
			this.length = length;
			this.isToken = isToken;
			this.token = token;
			this.occurency = occurency;
			this.rules = rules;
			this.intermediateValue = intermediateValue;
		}

		/// <summary>
		/// Gets a parsed rule that represents failure.
		/// </summary>
		public static ParsedRule Fail { get; } = new ParsedRule(false, -1, -1, 0, false, ParsedToken.Fail, -1, null, null);
	}
}