using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using RCLargeLanguageModels.Metadata;

namespace RCLargeLanguageModels.Completions
{
	/// <summary>
	/// Represents an immutable, completed general completion generated by LLM.
	/// </summary>
	public class Completion : ICompletion
	{
		/// <inheritdoc/>
		public string? Content { get; }

		/// <inheritdoc cref="ICompletion.PartialMetadata"/>
		public ImmutableArray<IMetadata> PartialMetadata { get; }
		IReadOnlyList<IMetadata> ICompletion.PartialMetadata => PartialMetadata;

		/// <inheritdoc cref="IMetadataProvider.Metadata"/>
		public MetadataCollection Metadata { get; }
		IMetadataCollection IMetadataProvider.Metadata => Metadata;
		IMetadataCollection ICompletion.Metadata => Metadata;

		/// <inheritdoc/>
		public IEnumerable<ITokenProbabilitiesMetadata> TokenProbabilities
			=> PartialMetadata.OfType<ITokenProbabilitiesMetadata>();

		/// <inheritdoc/>
		public IFinishReasonMetadata? FinishReason => Metadata.TryGet<IFinishReasonMetadata>();

		/// <summary>
		/// Creates a new instance of <see cref="Completion"/> class.
		/// </summary>
		/// <param name="content">The completion contents.</param>
		public Completion(string? content)
			: this(content, null, null)
		{
		}

		/// <summary>
		/// Creates a new instance of <see cref="Completion"/> class.
		/// </summary>
		/// <param name="content">The completion contents.</param>
		/// <param name="partialMetadata">The partial metadata for this completion.</param>
		/// <param name="completionMetadata">The completion metadata for this completion.</param>
		public Completion(
			string? content = null,
			IEnumerable<IMetadata>? partialMetadata = null,
			IEnumerable<IMetadata>? completionMetadata = null)
		{
			Content = content;
			PartialMetadata = partialMetadata?.ToImmutableArray() ?? ImmutableArray<IMetadata>.Empty;
			Metadata = completionMetadata != null
				? new MetadataCollection(completionMetadata)
				: MetadataCollection.Empty;
		}

		/// <summary>
		/// Creates a new instance of <see cref="Completion"/> class.
		/// </summary>
		/// <param name="content">The completion contents.</param>
		/// <param name="partialMetadata">The partial metadata for this completion.</param>
		/// <param name="completionMetadata">The completion metadata for this completion.</param>
		public Completion(
			string? content = null,
			ImmutableArray<IMetadata> partialMetadata = default,
			MetadataCollection? completionMetadata = null)
		{
			Content = content;
			PartialMetadata = partialMetadata;
			Metadata = completionMetadata ?? MetadataCollection.Empty;
		}

		/// <summary>
		/// Converts the completion to a partial completion.
		/// </summary>
		/// <returns></returns>
		public PartialCompletion AsPartialCompletion()
		{
			return new PartialCompletion(Content, PartialMetadata, Metadata);
		}
	}
}