using System;
using System.Collections.Generic;
using RCLargeLanguageModels.Metadata;

namespace RCLargeLanguageModels.Completions
{
	/// <summary>
	/// Represents a completion generated by LLM.
	/// </summary>
	public interface ICompletion : IContentHolder, IMetadataProvider
	{
		/// <summary>
		/// Gets the list of partial completion metadata (such as token logprobs: <see cref="ITokenProbabilitiesMetadata"/>).
		/// </summary>
		IReadOnlyList<IMetadata> PartialMetadata { get; }

		/// <summary>
		/// Gets the collection of completion metadata (such as stop reason: <see cref="IFinishReasonMetadata"/>).
		/// </summary>
		new IMetadataCollection Metadata { get; }

		/// <summary>
		/// Gets the list of token probabilities metadata (known as logprobs), may be empty.
		/// </summary>
		IEnumerable<ITokenProbabilitiesMetadata> TokenProbabilities { get; }

		/// <summary>
		/// Gets the finish reason metadata that caused the generation end, may be <see langword="null"/>.
		/// </summary>
		IFinishReasonMetadata? FinishReason { get; }
	}
}