using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using RCLargeLanguageModels.Metadata;
using RCLargeLanguageModels.Tasks;

namespace RCLargeLanguageModels.Completions
{
	/// <summary>
	/// Represents a streaming, partial completion generated by LLM.
	/// </summary>
	public class PartialCompletion : AsyncEnumerableBase<CompletionDelta>, ICompletion, INotifyPropertyChanged
	{
		private readonly object _lock = new object();
		private readonly StringBuilder _content;
		private readonly List<IMetadata> _partialMetadata;
		private MetadataCollection _metadata;

		/// <summary>
		/// Gets the count of stored deltas.
		/// </summary>
		public int DeltasCount => base.Count;

		/// <summary>
		/// Gets the completion token that can be used to track completion state.
		/// </summary>
		public new CompletionToken CompletionToken => base.CompletionToken;

		/// <summary>
		/// Gets the current completion contents.
		/// </summary>
		public string Content
		{
			get
			{
				lock (_lock)
					return _content.ToString();
			}
		}

		/// <summary>
		/// The currently stored partial metadata, such as token logprobs.
		/// </summary>
		public IReadOnlyList<IMetadata> PartialMetadata { get; }

		/// <summary>
		/// The completion metadata, will be empty until completed.
		/// </summary>
		public MetadataCollection Metadata => _metadata;
		IMetadataCollection IMetadataProvider.Metadata => _metadata;
		IMetadataCollection ICompletion.Metadata => _metadata;

		/// <summary>
		/// Gets the currently stored token probabilities metadata (known as logprobs), may be empty.
		/// </summary>
		public IEnumerable<ITokenProbabilitiesMetadata> TokenProbabilities
			=> PartialMetadata.OfType<ITokenProbabilitiesMetadata>();

		/// <summary>
		/// Gets the stop reason metadata that caused the generation end, may be <see langword="null"/> (especially if not completed).
		/// </summary>
		public IFinishReasonMetadata? FinishReason => Metadata?.TryGet<IFinishReasonMetadata>();

		/// <summary>
		/// The event is raised when a new part of the completion is added.
		/// </summary>
		public event EventHandler<CompletionDelta>? PartAdded;

		/// <summary>
		/// The event that is raised when message completes (successfully, cancelled or failed).
		/// </summary>
		public event EventHandler<CompletedEventArgs>? Completed
		{
			add => base.CompletionToken.Completed += value;
			remove => base.CompletionToken.Completed -= value;
		}

		/// <summary>
		/// The event is raised when a property of the partial completion is changed.
		/// </summary>
		public event PropertyChangedEventHandler? PropertyChanged;

		/// <summary>
		/// Creates an empty instance of <see cref="PartialCompletion"/> class.
		/// </summary>
		public PartialCompletion()
			: this(null, null, CompletionState.Incomplete, null, null)
		{
		}

		/// <summary>
		/// Creates a new instance of <see cref="PartialCompletion"/> class using the specified parameters.
		/// </summary>
		/// <remarks>
		/// Completion will be considered as succeed completed. All parameters can be <see langword="null"/>.
		/// </remarks>
		/// <param name="content">The main text content.</param>
		/// <param name="partialMetadata">The list of partial metadata.</param>
		/// <param name="metadata">The completion metadata.</param>
		public PartialCompletion(
			string? content = null,
			IEnumerable<IMetadata>? partialMetadata = null,
			IEnumerable<IMetadata>? metadata = null)
			: this(content, partialMetadata, CompletionState.Success, metadata, null)
		{
		}

		/// <summary>
		/// Creates a new instance of <see cref="PartialCompletion"/> class using the specified parameters.
		/// </summary>
		/// <remarks>
		/// All parameters can be <see langword="null"/> or <see langword="default"/>.
		/// </remarks>
		/// <param name="content">The main text content.</param>
		/// <param name="partialMetadata">The list of partial metadata.</param>
		/// <param name="completionState">The completion state of the partial completion.</param>
		/// <param name="completionMetadata">
		/// The completion metadata.
		/// Will be ignored when <paramref name="completionState"/>==<see cref="CompletionState.Incomplete"/>.
		/// </param>
		/// <param name="completionException">
		/// The exception that caused the <paramref name="completionState"/>==<see cref="CompletionState.Failed"/>.
		/// Must me non-<see langword="null"/> when using with failed completion state.
		/// </param>
		public PartialCompletion(
			string? content = null,
			IEnumerable<IMetadata>? partialMetadata = null,
			CompletionState completionState = CompletionState.Incomplete,
			IEnumerable<IMetadata>? completionMetadata = null,
			Exception? completionException = null)
			: base(GetInitialDelta(content, partialMetadata), completionState, completionException)
		{
			_content = new StringBuilder(content ?? string.Empty);
			_partialMetadata = partialMetadata?.ToList() ?? new List<IMetadata>();
			PartialMetadata = _partialMetadata.AsReadOnly();

			if (_metadata != null && completionState != CompletionState.Incomplete)
				_metadata = new MetadataCollection(completionMetadata ?? Enumerable.Empty<IMetadata>());
			else
				_metadata = MetadataCollection.Empty;

		}

		private static IEnumerable<CompletionDelta> GetInitialDelta(
			string? content,
			IEnumerable<IMetadata>? partialMetadata)
		{
			if (string.IsNullOrEmpty(content) && (partialMetadata == null || !partialMetadata.Any()))
				return Enumerable.Empty<CompletionDelta>();

			return new[] { new CompletionDelta(content, partialMetadata) };
		}

		/// <summary>
		/// Adds a delta part to the completion. If delta is empty, it will ignored.
		/// </summary>
		/// <param name="deltaContent">The delta of main text content.</param>
		/// <param name="newPartialMetadata">The new partial metadata.</param>
		public void Add(
			string? deltaContent = null,
			IEnumerable<IMetadata>? newPartialMetadata = null)
		{
			Add(new CompletionDelta(deltaContent, newPartialMetadata));
		}

		/// <summary>
		/// Adds a delta part to the completion. If delta is empty, it will ignored.
		/// </summary>
		/// <param name="delta">The delta of the completion.</param>
		/// <exception cref="ArgumentNullException">Thrown when <paramref name="delta"/> is <see langword="null"/>.</exception>
		public new void Add(CompletionDelta delta)
		{
			if (delta == null)
				throw new ArgumentNullException(nameof(delta));
			if (delta.IsEmpty)
				return;

			CompletionToken.ThrowIfComplete();

			lock (_lock)
			{
				if (!string.IsNullOrEmpty(delta.DeltaContent))
				{
					_content.Append(delta.DeltaContent);
					PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(Content)));
				}

				if (!delta.NewPartialMetadata.IsNullOrEmpty())
				{
					_partialMetadata.AddRange(delta.NewPartialMetadata!);
					PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(PartialMetadata)));
				}

				base.Add(delta);
			}

			PartAdded?.Invoke(this, delta);
		}

		private void CompletePrivate(IEnumerable<IMetadata>? completionMetadata)
		{
			CompletionToken.ThrowIfComplete();

			if (completionMetadata != null)
				_metadata = new MetadataCollection(completionMetadata);
			else
				_metadata = MetadataCollection.Empty;

			PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(Metadata)));
		}

		/// <summary>
		/// Completes partial completion with <see cref="CompletionState.Success"/> and provided metadata.
		/// </summary>
		/// <param name="completionMetadata">The optional completion metadata.</param>
		/// <exception cref="InvalidOperationException">Thrown if completion is already completed.</exception>
		public void Complete(IEnumerable<IMetadata>? completionMetadata = null)
		{
			lock (_lock)
			{
				CompletePrivate(completionMetadata);
				base.Finish();
			}
		}

		/// <summary>
		/// Completes partial completion with <see cref="CompletionState.Cancelled"/> and provided metadata.
		/// </summary>
		/// <param name="completionMetadata">The optional completion metadata.</param>
		/// <exception cref="InvalidOperationException">Thrown if completion is already completed.</exception>
		public void Cancel(IEnumerable<IMetadata>? completionMetadata = null)
		{
			lock (_lock)
			{
				CompletePrivate(completionMetadata);
				base.Cancel();
			}
		}

		/// <summary>
		/// Completes partial completion with <see cref="CompletionState.Failed"/> and provided exception and metadata.
		/// </summary>
		/// <param name="exception">The exception that caused the completion failure.</param>
		/// <param name="completionMetadata">The optional completion metadata.</param>
		/// <exception cref="InvalidOperationException">Thrown if completion is already completed.</exception>
		public void Fail(Exception exception, IEnumerable<IMetadata>? completionMetadata = null)
		{
			lock (_lock)
			{
				CompletePrivate(completionMetadata);
				base.Fail(exception);
			}
		}

		/// <summary>
		/// Completes partial completion with <see cref="CompletedEventArgs"/> and metadata.
		/// </summary>
		/// <param name="args">The completed event args to import from.</param>
		/// <param name="completionMetadata">The optional completion metadata.</param>
		/// <exception cref="InvalidOperationException">Thrown if completion is already completed.</exception>
		public void ImportCompletion(CompletedEventArgs args, IEnumerable<IMetadata>? completionMetadata = null)
		{
			lock (_lock)
			{
				CompletePrivate(completionMetadata);
				base.ImportCompletion(args);
			}
		}

		/// <summary>
		/// Gets awaiter for this partial completion.
		/// </summary>
		/// <returns>The <see cref="CompletionToken"/> that represents the awaiter.</returns>
		public CompletionToken GetAwaiter()
		{
			return CompletionToken;
		}

		/// <summary>
		/// Converts the partial completion to a completed completion.
		/// </summary>
		public Completion AsCompletion()
		{
			lock (_lock)
			{
				return new Completion(
					Content,
					PartialMetadata,
					Metadata);
			}
		}

		/// <summary>
		/// Creates a copy of the partial assistant message.
		/// </summary>
		/// <returns></returns>
		public PartialCompletion Copy()
		{
			lock (_lock)
			{
				return new PartialCompletion(
					Content,
					PartialMetadata,
					CompletionToken.State,
					Metadata,
					CompletionToken.Exception);
			}
		}
	}
}